name: all_jobs

on:
  push:
    branches: [ master ]
    paths: ['code_server/*','.github/workflows/code_server.yml']
  schedule:
    - cron: '50 0 * * 0'

jobs:    
  code_server:
    build:
      runs-on: ubuntu-latest
      steps:   
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          con_name: xyzzpwn/code_server 
          Docker_file_dir: code_server
        run: |
          cd $Docker_file_dir
          pwd
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime;
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          export con_time_name=$con_name:$(date +%Y%m%d%H%M%S)
          export con_relese_name=$con_name:latest
          docker build . --tag $con_time_name --no-cache
          docker push $con_time_name
          docker tag $con_time_name $con_relese_name
          docker push $con_relese_name
          
  downloadm3u8:
    build:
      runs-on: ubuntu-latest
      steps:   
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          con_name: xyzzpwn/downloadm3u8 
          Docker_file_dir: downloadm3u8
        run: |
          cd $Docker_file_dir
          pwd
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime;
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          export con_time_name=$con_name:$(date +%Y%m%d%H%M%S)
          export con_relese_name=$con_name:latest
          docker build . --tag $con_time_name
          docker push $con_time_name
          docker tag $con_time_name $con_relese_name
          docker push $con_relese_name
          
  hexo:
    build:
      runs-on: ubuntu-latest
      steps:   
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          con_name: xyzzpwn/hexo 
          Docker_file_dir: hexo
        run: |
          cd $Docker_file_dir
          pwd
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime;
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          export con_time_name=$con_name:$(date +%Y%m%d%H%M%S)
          export con_relese_name=$con_name:latest
          docker build . --tag $con_time_name
          docker push $con_time_name
          docker tag $con_time_name $con_relese_name
          docker push $con_relese_name

  nginx_proxy:
    build:
      runs-on: ubuntu-latest
      steps:   
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          con_name: xyzzpwn/nginx_proxy 
          Docker_file_dir: nginx_proxy
        run: |
          cd $Docker_file_dir
          pwd
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime;
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          export con_time_name=$con_name:$(date +%Y%m%d%H%M%S)
          export con_relese_name=$con_name:latest
          docker build . --tag $con_time_name
          docker push $con_time_name
          docker tag $con_time_name $con_relese_name
          docker push $con_relese_name
          