name: Docker Image CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '50 23 * * 6'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime;
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
        export con_name=xyzzpwn/hexo
        export con_time_name=$con_name:$(date +%Y%m%d%H%M%S)
        export con_relese_name=$con_name:latest
        docker build . --file ./Dockerfile --tag $con_time_name
        docker push $con_time_name
        docker tag $con_time_name $con_relese_name
        docker push $con_relese_name
        
